version: "3"
services:
  app:
    build: ./src/.
    environment:
      URL: https://google.com
      #USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
      #CRON_STRING: '*/30 * * * * *'
      #DEBUG: false